name: Angular CI

# Gatilhos: Roda em pull requests ou pushes para a branch main
on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint Angular Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

  discord:
    # Garante que este job só rodará DEPOIS que o job 'lint' terminar com sucesso
    needs: lint
    runs-on: ubuntu-latest
    steps:
      # 1. Faz o checkout do código com o histórico completo (MUITO IMPORTANTE!)
      # A nova Action também precisa do histórico para listar os commits.
      - name: Checkout with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Usa a nova Action 'Sniddl/discord-commits' para enviar a notificação
      - name: Send Discord Commit Notification
        uses: Sniddl/discord-commits@v1.6
        with:
          # O nome do parâmetro aqui é 'webhook', não 'webhook_url'
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          
          # Parâmetros extras que você sugeriu
          template: "avatar-with-link"
          include-extras: true